"""Create Pofile Table

Revision ID: 9bd3912a2aae
Revises: c5264431caaf
Create Date: 2023-11-19 12:19:44.751552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9bd3912a2aae"
down_revision: Union[str, None] = "c5264431caaf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profiles",
        sa.Column("first_name", sa.String(length=40), nullable=True),
        sa.Column("last_name", sa.String(length=40), nullable=True),
        sa.Column("bio", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.add_column(
        "posts", sa.Column("body", sa.Text(), server_default="", nullable=False)
    )
    op.drop_column("posts", "ode")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts",
        sa.Column("ode", sa.TEXT(), server_default=sa.text("('')"), nullable=False),
    )
    op.drop_column("posts", "body")
    op.drop_table("profiles")
    # ### end Alembic commands ###
